sudo: false
dist: trusty

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - dev
    - dev-composer

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
  - name: "PHP 7.4 / Nightly WordPress"
    php: "7.4snapshot"
    env: WP_VERSION=nightly WP_MULTISITE=0
  - name: "PHP 7.4 / Nightly WordPress multisite"
    php: "7.4snapshot"
    env: WP_VERSION=nightly WP_MULTISITE=1
  - name: "PHP 7.4 / Latest WordPress"
    php: "7.4snapshot"
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 7.4 / Latest WordPress multisite"
    php: "7.4snapshot"
    env: WP_VERSION=latest WP_MULTISITE=1
  - name: "PHP 7.3 / Latest WordPress"
    php: "7.3"
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 7.3 / Latest WordPress multisite"
    php: "7.3"
    env: WP_VERSION=latest WP_MULTISITE=1
  - name: "PHP 7.2 / Latest WordPress"
    php: "7.2"
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 7.2 / Latest WordPress multisite"
    php: "7.2"
    env: WP_VERSION=latest WP_MULTISITE=1
  - name: "PHP 7.1 / Latest WordPress"
    php: "7.1"
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 7.1 / Latest WordPress multisite"
    php: "7.1"
    env: WP_VERSION=latest WP_MULTISITE=1
  - name: "PHP 7.0 / Latest WordPress"
    php: "7.0"
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 7.0 / Latest WordPress multisite"
    php: "7.0"
    env: WP_VERSION=latest WP_MULTISITE=1
  - name: "PHP 5.6 / Latest WordPress"
    php: "5.6"
    env: WP_VERSION=latest WP_MULTISITE=0
  - name: "PHP 5.6 / Latest WordPress multisite"
    php: "5.6"
    env: WP_VERSION=latest WP_MULTISITE=1
  - name: "PHP 5.6 / Minimum supported WordPress 4.9"
    php: "5.6"
    env: WP_VERSION=4.9 WP_MULTISITE=0
  - name: "PHP 5.6 / Minimum supported WordPress 4.9 multisite"
    php: "5.6"
    env: WP_VERSION=4.9 WP_MULTISITE=1

before_install:
  # Speed up build time by disabling Xdebug.
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  - phpenv config-rm xdebug.ini || echo "xdebug not available for PHP $TRAVIS_PHP_VERSION"

install:
  - composer install

script:
  # Search for PHP syntax errors.
  # - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Show a list of installed coding standards.
  - composer lint-i
  # Run against installed coding standards.
  - composer lint
